### PR TITLE
Changes required to provide a merging script which is aware of mmQc

### PR DESCRIPTION
**Pull request by keiranmraine**
Still setting up additional flow in internal large-scale CI for new elements

### CODE REVIEW

**Comment by keiranmraine** [comment]
Internal CI report: https://casm.pages.internal.sanger.ac.uk/cit-github/pcap-core/results/feature-mergeOrMark/summary/

**Comment by keiranmraine** [comment]
@AndyMenzies there is a review pending from 20th December

**Comment by AndyMenzies** [comment]
Code looks good.  WGS results are good. Do we know why the results for Amplicon and WXS differed from previous?

**Comment by keiranmraine** [comment]
> Do we know why the results for Amplicon and WXS differed from previous?

Those are physical remaps where we expect a small variance in result (as described in the report).

MARK/MERGE is the change to the code, they are exact as mapping is precalculated, only merging or duplicate marking (with inline merging) occur.  These are via completely new routines and script.

**Comment by keiranmraine** [comment]
@AndyMenzies also, if you compare to previous reports for other tags, they are the same differences so actually stable against the new container.

**Comment by AndyMenzies** [comment]
Agreed, all looks good to me.

**Comment by keiranmraine** [comment]
This has been pulled into the bwamem2 branch as already approved.

**Pull request closed without merging**
