### PR TITLE
Feature/add threadpool

### PR DESCRIPTION
**Pull request by drjsanger**
@keiranmraine Please review. Then I can make a release candidate from the branch for testing

### CODE REVIEW

**Comment by keiranmraine** [comment]
This looks good, I'm happy to build and test from the branch without a tag.

**Comment by drjsanger** [comment]
@keiranmraine Updated to include proper sentinel fixes.

**Comment by keiranmraine** [comment]
Ran a small mapping flow with updated PCAP-core, runtime reduces and no change to *.bas output.

@drjsanger can you review these few lines: https://github.com/cancerit/PCAP-core/pull/20/commits/9f63d2ba085847fba92d96d72213cd7224372457

**Comment by keiranmraine** [comment]
@drjsanger FYI it appears for BAM exceeding 2 CPUs for bam_stats has no additional advantage, happily it does halve the runtime of bam_stats.

**Comment by keiranmraine** [comment]
Discussed with @drjsanger (as his mac with Systems).  Good to go

**Pull request merged**
